# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- azure-pipelines

pool:
  vmImage: 'vs2017-win2016'
strategy:
  matrix:
    Python37:
      python.version: '3.7'

steps:
- checkout: self
  fetchDepth: 10
- script: git submodule update --init --recursive
  displayName: 'Fetch submodules'
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements-dev.txt
  displayName: 'Install dependencies'

- script: |
    python setup.py install
  displayName: 'Build'

- script: |
    python -c 'import kaa._kaa'
  displayName: 'Test import'
