# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

name: 'Build macOS'
trigger:
- azure-pipelines

pool:
  vmImage: 'macOS-10.13'
strategy:
  matrix:
    # Python36:
    #   python.version: '3.6'
    # Python37:
    #   python.version: '3.7'
    Python38:
      python.version: '3.8'

steps:
- checkout: self

- script: |
    git clone https://github.com/maniek2332/kaacore --recurse-submodules -b macos-test
  displayName: 'Fetch submodules'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- bash: |
    VERSION=`python -c "import versioneer; print(versioneer.get_versions()['version'])"`
    echo $VERSION
    echo "##vso[task.setvariable variable=dist_version]$VERSION"
  displayName: 'Getting version string'

- script: |
    python -m pip install --upgrade pip
    pip install Cython==0.29.14 scikit-build==0.10.0 delocate
  displayName: 'Install dependencies'

- script: |
    python setup.py bdist_wheel
  displayName: 'Build'

- script: ls dist/
  displayName: 'List wheels'

- publish: dist/
  artifact: "kaa_build_$(dist_version)"
