# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

name: 'Build macOS'
trigger:
- azure-pipelines

pool:
  vmImage: 'macOS-10.13'
strategy:
  matrix:
    # Python36:
    #   python.version: '3.6'
    Python37:
      python.version: '3.7'
    # Python38:
    #   python.version: '3.8'

steps:
- checkout: self

- script: |
    git clone https://github.com/maniek2332/kaacore --recurse-submodules -b macos-test
  displayName: 'Fetch submodules'

# - task: UsePythonVersion@0
#   inputs:
#     versionSpec: '$(python.version)'
#     architecture: 'x64'
#   displayName: 'Use Python $(python.version)'

- script: bash macos-install-python.sh $(python.version)
  displayName: 'Use Python $(python.version)'

- bash: |
    VERSION=`python -c "import versioneer; print(versioneer.get_versions()['version'])"`
    echo $VERSION
    echo "##vso[task.setvariable variable=dist_version]$VERSION"
  displayName: 'Getting version string'

- script: |
    /usr/local/bin/python --version
    /usr/local/bin/python -m pip install --upgrade pip
    /usr/local/bin/python -m pip install Cython==0.29.14 scikit-build==0.10.0 delocate
  displayName: 'Install dependencies'

- script: |
    export PATH=/Library/Frameworks/Python.framework/Versions/$(python.version)/bin:$PATH
    /usr/local/bin/python setup.py bdist_wheel --plat-name macosx-10.9-x86_64 -- -DKAA_BUNDLE_SDL:BOOL=OFF
  displayName: 'Build'

- script: ls dist/
  displayName: 'List wheels'

- script: |
    export PATH=/Library/Frameworks/Python.framework/Versions/$(python.version)/bin:$PATH
    SDL2_LIB_PATH=$(System.DefaultWorkingDirectory)/_skbuild/macosx-10.9-x86_64-$(python.version)/cmake-build/kaacore/third_party/sdl2/
    echo $SDL2_LIB_PATH
    ls $SDL2_LIB_PATH
    export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:$SDL2_LIB_PATH
    delocate-listdeps dist/*.whl
    delocate-listdeps --all dist/*.whl
    mkdir fixed_dist/
    delocate-wheel -w fixed_dist -v dist/*.whl
    delocate-listdeps --all fixed_dist/*.whl
  displayName: 'Delocate wheel'

- script: |
    export PATH=/Library/Frameworks/Python.framework/Versions/$(python.version)/bin:$PATH
    mkdir test_dir
    cd test_dir
    /usr/local/bin/python -m venv venv_test_$(python.version)
    ./venv_test_$(python.version)/bin/python -m pip install --upgrade pip
    ./venv_test_$(python.version)/bin/python -m pip install --upgrade ../fixed_dist/*.whl
    ./venv_test_$(python.version)/bin/python -c "import kaa._kaa"

- publish: fixed_dist/
  artifact: "kaa_build_$(dist_version)"
